apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: frontend

data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb/frontend"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: frontend

spec:
  replicas: 1
  selector:
     matchLabels:
      project: roboshop
      tier: frontend
      component: frontend

  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
    spec:
      
      containers:
      - name: frontend
        image: sreenivaschitti/frontend:1.0.0
        imagePullPolicy: Always
     
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
           port: 80
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 5

        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 2
          periodSeconds: 10
           

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: frontend

spec:
  type: LoadBalancer
  selector:
    project: roboshop
    tier: frontend
    component: frontend

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80