apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping

data:
    CART_ENDPOINT="cart:8080" 
    DB_HOST="mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping

spec:
  replicas: 1
  selector:
     matchLabels:
      project: roboshop
      tier: backend
      component: shipping

  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: shipping
    spec:
      
      containers:
      - name: shipping
        image: sreenivaschitti/shipping:1.0.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
           

---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping

spec:
  selector:
    project: roboshop
    tier: backend
    component: shipping

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080