apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq

data:
   RABBITMQ_DEFAULT_USER: roboshop
   RABBITMQ_DEFAULT_PASS: roboshop123 
   container_name: rabbitmq

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq

spec:
  replicas: 1
  selector:
     matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq

  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: rabbitmq
       
           

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq

spec:
  selector:
    project: roboshop
    tier: db
    component: rabbitmq

  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672