apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user

data:
    MONGO: "true"
    MONGO_URL: "mongodb://mongodb:27017/users"
    REDIS_HOST: "redis"
    SERVICE_NAME: "user"
    PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user

spec:
  replicas: 1
  selector:
     matchLabels:
      project: roboshop
      tier: backend
      component: user

  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: user
    spec:
      
      containers:
      - name: user
        image: sreenivaschitti/user:1.0.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: user
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
           port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
           

---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user

spec:
  selector:
    project: roboshop
    tier: backend
    component: user

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080